---
# tasks file for nginx
    - name: install tools
      pip: name=httplib2

    - name: install nginx
      yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present update_cache=yes

    - name: latest nginx
      yum: name=nginx state=latest

    - name: configure nginx site
      template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/default.conf mode=0644
      with_dict: sites
      notify: restart nginx

    - name: ensure nginx started
      service: name=nginx state=started enabled=yes
