---
- hosts: loadbalancer
  become: true
  tasks:
    - name: install tools
      yum: name={{item}} state=present update_cache=yes
      with_items:
        -httplib2

    - name: install nginx
      yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm state=present update_cache=yes

    - name: latest nginx
      yum: name=nginx state=latest

    - name: Create Directory
      file: path=/etc/nginx/sites-available state=directory mode=0644
      file: path=/etc/nginx/sites-available/demo state=directory mode=0644
      file: path=/etc/nginx/sites-enabled state=directory mode=0644
      notify: restart nginx
    
    - name: ensure nginx started
      service: name=nginx state=started enabled=yes

    - name: configure nginx site
      template: src=templates/nginx.conf.j2 dest=/etc/nginx/sites-available/demo/ mode=0644
      notify: restart nginx

    - name: de-activate default nginx site
      file: path=/etc/nginx/conf.d/default.conf state=absent
      notify: restart nginx

    - name: activate demo nginx site
      file: src=/etc/nginx/sites-available/demo dest=/etc/nginx/sites-enabled/demo state=link
      notify: restart nginx

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted


