---
# tasks file for control
  tasks:
    - name: install tools
      yum: name={{item}} state=present update_cache=yes
      with_items:
        - curl
    
    - name: install httplib2
      yum: name={{item}} state=present update_cache=yes
      with_items:
        -httplib2